# Generated by Django 3.1.2 on 2020-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('player_x', models.CharField(max_length=64)),
                ('player_o', models.CharField(max_length=64)),
            ],
        ),
    ]
